### ISSUE TITLE
insecure authentication rules

### ISSUE THREAD

**Issue by labsvisual** [dandesz198/pass#2]
This is [Shreyansh](https://hashnode.com/labsvisua) from Hashnode and I just saw this repository. I was going over the code and [this](https://github.com/dandesz198/pass/blob/master/backend/utils/hash.js) file contains code which has frightened me. 

Hashing passwords, or any data for that matter, should be done with some time-cost composites; an example is `bcrypt`.

And the code standard is all over the place; if you want a manageable solution, I would advice you to use some sort of linter to enforce a strict code-style across the entirety of the project. 

All in all, this looks like a really cool solution and if you need help in interfacing the software with the hardware, I am always there. I can also help you with the electronics part of it, should you want! Cheers!

**Comment by danger9224** [comment]
Hey! 👋 
Thank you so much. Security is playing a key role in this project as I want it to be live in a real city, thus it obviously needs to live up to some privacy standards.
The backend's code base at this point is just some copy-pasta from a previous project, and I just started rewriting it, I'll be able to commit the new backend in a few hours if everything goes well, and it will definietly fix this issue, thanks again for noticing me.
About the linting: do you think `eslint` may be suitable for this type of project?

**Comment by labsvisual** [comment]
No worries at all! You might want to use some sort of asymmetric pair verification over, I guess, DHKE to verify the authenticity of the person/entity using the card. 

`eslint` should be more than enough for the job. I might, however, recommend using [xo](https://www.npmjs.com/package/xo).
